# Generated by Django 5.1.7 on 2025-04-15 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_catagory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("image", models.URLField()),
                ("price_level", models.CharField(max_length=50)),
                ("google_rating", models.FloatField()),
                ("number_of_reviews", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="catagory",
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["place_id"], name="restaurants_place_i_1b378b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="restaurants_user_id_374b6d_idx"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="categories",
            field=models.ManyToManyField(blank=True, to="restaurants.category"),
        ),
        migrations.AddField(
            model_name="restaurantreview",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="restaurantreview",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurants.review"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["place_id"], name="restaurants_place_i_cf340a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["name"], name="restaurants_name_0080ba_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="restaurantreview",
            unique_together={("restaurant", "review")},
        ),
    ]
