# Generated by Django 5.1.7 on 2025-03-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_kyc_document_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Documents Sent for Verification"),
                    ("verified", "Your Document has been Verified"),
                    ("rejected", "Verification Rejected"),
                    ("kyc_required", "Please Proceed to KYC Verification"),
                ],
                default="kyc_required",
                max_length=20,
            ),
        ),
    ]
